### ISSUE TITLE
Alert Toast (.hud display mode) large text not fit to the screen

### ISSUE THREAD

**Issue by iosAnkit** [elai950/AlertToast#83]
`
struct ContentView: View {
    
    @State private var showToast = false
    
    var body: some View {
        VStack {
            Button("Show Toast"){
                 showToast.toggle()
            }
        }
        .toast(isPresenting: $showToast){
            AlertToast(displayMode: .hud, type: .regular, title: "I want to show large message in this alert toast but the text is truncated.")
        }
    }
}

`

![Simulator Screenshot - iPhone 15 Pro - 2023-11-02 at 12 32 58](https://github.com/elai950/AlertToast/assets/24468775/7de920ca-a583-403c-a42e-d14a03b9e4c5)

**Comment by iosAnkit** [comment]
fixed in 1.3.9

**Comment by guyaumetremblay** [comment]
@iosAnkit is it ? I have the 1.3.9 and the source code still have the deleted lines from the commit.
